# requires root privilege
sudo: required
language: generic 

# service need for the project
services:
  - docker

# before installation
before_install:
  - docker build -t michael/ngix-web -f Dockerfile.dev .

# after installation is completed
script:
  - docker run -e CI=true michael/ngix-web npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ngix-web2"
  env: "Ngixweb2-env"
  bucket_name: "elasticbeanstalk-us-east-2-569819565829"
  bucket_path: "ngix-web2"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: $aws_seceret_key
